function integral(values, width, height){
  const stride=width+1, out=new Float64Array((width+1)*(height+1));
  for(let y=0;y<height;y++){let row=0;for(let x=0;x<width;x++){row+=values[y*width+x];out[(y+1)*stride+(x+1)]=out[y*stride+(x+1)]+row;}}
  return out;
}
function boxMean(ii,width,height,x,y,r){const stride=width+1,x0=Math.max(0,x-r),y0=Math.max(0,y-r),x1=Math.min(width-1,x+r),y1=Math.min(height-1,y+r);const sum=ii[(y1+1)*stride+(x1+1)]-ii[y0*stride+(x1+1)]-ii[(y1+1)*stride+x0]+ii[y0*stride+x0];return sum/((x1-x0+1)*(y1-y0+1));}
function binaryWindow(mask,width,height,r,mode){const ii=integral(mask,width,height),out=new Uint8Array(mask.length),stride=width+1;for(let y=0;y<height;y++)for(let x=0;x<width;x++){const x0=Math.max(0,x-r),y0=Math.max(0,y-r),x1=Math.min(width-1,x+r),y1=Math.min(height-1,y+r),sum=ii[(y1+1)*stride+(x1+1)]-ii[y0*stride+(x1+1)]-ii[(y1+1)*stride+x0]+ii[y0*stride+x0],total=(x1-x0+1)*(y1-y0+1);out[y*width+x]=mode==='dilate'?(sum>0?1:0):(sum>=total?1:0);}return out;}
function morph(mask,width,height,r){let out=mask;for(let i=0;i<2;i++)out=binaryWindow(binaryWindow(out,width,height,r,'dilate'),width,height,r,'erode');out=binaryWindow(binaryWindow(out,width,height,r,'erode'),width,height,r,'dilate');return out;}
function components(mask,width,height){const seen=new Uint8Array(mask.length),found=[],areaAll=width*height,dirs=[-1,1,-width,width,-width-1,-width+1,width-1,width+1];for(let start=0;start<mask.length;start++){if(!mask[start]||seen[start])continue;const stack=[start];seen[start]=1;let area=0,minX=width,maxX=0,minY=height,maxY=0;while(stack.length){const p=stack.pop(),y=Math.floor(p/width),x=p-y*width;area++;minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);for(const d of dirs){const q=p+d;if(q<0||q>=mask.length||seen[q]||!mask[q])continue;const qy=Math.floor(q/width),qx=q-qy*width;if(Math.abs(qx-x)>1||Math.abs(qy-y)>1)continue;seen[q]=1;stack.push(q);}}const w=maxX-minX+1,h=maxY-minY+1,aspect=w/h,fill=area/(w*h),share=area/areaAll;if(share<0.006||share>0.28||aspect<0.58||aspect>1.72||fill<0.55)continue;found.push({x:minX,y:minY,width:w,height:h,area,fill,cx:(minX+maxX)/2,cy:(minY+maxY)/2});}return found;}
function sortReadingOrder(items){if(items.length<2)return items;const avgH=items.reduce((s,i)=>s+i.height,0)/items.length,tolerance=avgH*.55,rows=[];for(const item of [...items].sort((a,b)=>a.cy-b.cy||a.cx-b.cx)){let row=rows.find(r=>Math.abs(r.cy-item.cy)<=tolerance);if(!row){row={cy:item.cy,items:[]};rows.push(row)}row.items.push(item);row.cy=row.items.reduce((s,i)=>s+i.cy,0)/row.items.length;}rows.sort((a,b)=>a.cy-b.cy);return rows.flatMap(r=>r.items.sort((a,b)=>a.cx-b.cx));}
async function bitmapFromBlob(blob){if(globalThis.createImageBitmap)return createImageBitmap(blob);const url=URL.createObjectURL(blob);try{return await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=url})}finally{URL.revokeObjectURL(url)}}
export async function detectCoins(blob,{maxDimension=700}={}){const bitmap=await bitmapFromBlob(blob),sourceWidth=bitmap.width,sourceHeight=bitmap.height,scale=Math.min(1,maxDimension/Math.max(sourceWidth,sourceHeight)),width=Math.max(1,Math.round(sourceWidth*scale)),height=Math.max(1,Math.round(sourceHeight*scale)),canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(bitmap,0,0,width,height);const data=ctx.getImageData(0,0,width,height).data,gray=new Float32Array(width*height),sat=new Float32Array(width*height);for(let i=0,p=0;i<data.length;i+=4,p++){const r=data[i],g=data[i+1],b=data[i+2],max=Math.max(r,g,b),min=Math.min(r,g,b);gray[p]=.299*r+.587*g+.114*b;sat[p]=max-min;}const radius=Math.max(24,Math.round(Math.min(width,height)*.08)),gi=integral(gray,width,height),si=integral(sat,width,height),mask=new Uint8Array(width*height);for(let y=0;y<height;y++)for(let x=0;x<width;x++){const p=y*width+x,gMean=boxMean(gi,width,height,x,y,radius),sMean=boxMean(si,width,height,x,y,radius);if(gMean-gray[p]>9||sat[p]-sMean>16)mask[p]=1;}const mr=Math.max(2,Math.round(Math.min(width,height)*.005)),cleaned=morph(mask,width,height,mr),detected=sortReadingOrder(components(cleaned,width,height));const boxes=detected.map((d,index)=>{const pad=Math.round(Math.max(d.width,d.height)*.11),x=Math.max(0,d.x-pad),y=Math.max(0,d.y-pad),x2=Math.min(width,d.x+d.width+pad),y2=Math.min(height,d.y+d.height+pad);return {index:index+1,x:x/scale,y:y/scale,width:(x2-x)/scale,height:(y2-y)/scale,confidence:'experimental'};});bitmap.close?.();return {count:boxes.length,boxes,analysisWidth:width,analysisHeight:height};}
export async function cropCoin(blob,box,type='image/jpeg'){const bitmap=await bitmapFromBlob(blob),canvas=document.createElement('canvas'),x=Math.max(0,Math.floor(box.x)),y=Math.max(0,Math.floor(box.y)),w=Math.min(bitmap.width-x,Math.ceil(box.width)),h=Math.min(bitmap.height-y,Math.ceil(box.height));canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(bitmap,x,y,w,h,0,0,w,h);bitmap.close?.();return await new Promise(resolve=>canvas.toBlob(resolve,type==='image/png'?'image/png':'image/jpeg',.92));}
