import './coin-world19-final-gap-closer.js';
import {chooseBestOcr,mergeOcrText} from './coin-ocr-quality.mjs';
let workerPromise=null,busy=false;
const TESSERACT_URL='https://cdn.jsdelivr.net/npm/tesseract.js@7/dist/tesseract.esm.min.js';
async function worker(){if(!workerPromise)workerPromise=(async()=>{const {createWorker}=await import(TESSERACT_URL);return createWorker('eng',1,{logger:m=>{const el=document.querySelector('#ocr-status');if(el&&m.status)el.textContent=`OCR: ${m.status}${m.progress!=null?` ${Math.round(m.progress*100)}%`:''}`;}})})();return workerPromise;}
function field(card,key){return card?.querySelector(`[data-field="${key}"]`)}
function setField(card,key,value){const el=field(card,key);if(!el)return;el.value=value;el.dispatchEvent(new Event(el.tagName==='SELECT'?'change':'input',{bubbles:true}));}
function addButtons(){document.querySelectorAll('.record-card').forEach(card=>{const actions=card.querySelector('.record-actions');if(!actions||actions.querySelector('[data-action="run-ocr"]'))return;const b=document.createElement('button');b.type='button';b.dataset.action='run-ocr';b.textContent='Read visible text';actions.prepend(b);});}
function installStatus(){if(document.querySelector('#ocr-status'))return;const records=document.querySelector('#records');if(!records)return;const p=document.createElement('p');p.id='ocr-status';p.className='help';p.textContent='OCR is optional. It runs in your browser and only adds visible-text clues after a confidence check.';records.before(p);}
async function recognizeImage(img,w){const variants=[];for(const psm of [6,11]){await w.setParameters({tessedit_pageseg_mode:String(psm),preserve_interword_spaces:'1'});const result=await w.recognize(img);variants.push({text:result.data?.text||'',confidence:result.data?.confidence||0});}return chooseBestOcr(variants);}
async function run(card,button){if(busy)return;const imgs=[...card.querySelectorAll('.record-images img')];if(!imgs.length)return;busy=true;button.disabled=true;const status=document.querySelector('#ocr-status');try{if(status)status.textContent='OCR: loading browser text reader…';const w=await worker(),signals=[];for(const img of imgs){const signal=await recognizeImage(img,w);if(signal.accepted)signals.push(signal);}const best=chooseBestOcr(signals);if(!best.accepted){if(status)status.textContent='OCR found no sufficiently reliable visible text. Nothing was added.';return;}const clues=field(card,'referenceClues'),merged=mergeOcrText(clues?.value,best.text);setField(card,'referenceClues',merged);const notes=field(card,'notes');if(notes)setField(card,'notes',mergeOcrText(notes?.value,`OCR ${best.level} confidence (${Math.round(best.confidence)}%): ${best.text}`));if(status)status.textContent=`OCR added a ${best.level}-confidence text clue (${Math.round(best.confidence)}%). Review it before checking the public reference.`;}catch(err){console.error(err);if(status)status.textContent='OCR could not run. No inventory data was changed; manual visible-text entry remains available.';}finally{busy=false;button.disabled=false;}}
const observer=new MutationObserver(()=>addButtons());observer.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('DOMContentLoaded',()=>{installStatus();addButtons();});document.addEventListener('click',e=>{const b=e.target.closest('button[data-action="run-ocr"]');if(!b)return;e.preventDefault();e.stopPropagation();run(b.closest('.record-card'),b);},true);
