import './coin.js';
import {EURO_REFERENCE_DB,euroReferenceRows,euroReferenceStats} from './euro-reference.mjs';
import {EURO_SERIES_REFERENCE_DB,euroSeriesRows,euroSeriesStats} from './euro-series-reference.mjs';
import {classifyEuroTwo,euroCommemorativeRows} from './euro-commemorative-reference.mjs';
import {GERMANY_HISTORICAL_REFERENCE_DB,germanyHistoricalRows} from './europe-historical-germany.mjs';
import {GERMANY_5DM_COMM} from './germany-5dm-commemoratives.mjs';
import {GERMANY_10DM_COMM} from './germany-10dm-commemoratives.mjs';
import {GERMANY_DDR_REFERENCE_DB,germanyDdrRows} from './germany-ddr-reference.mjs';
const norm=v=>String(v||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/€/g,'euro').replace(/\s+/g,' ');
const value=(card,key)=>card?.querySelector(`[data-field="${key}"]`)?.value||'';
const set=(card,key,val)=>{const el=card?.querySelector(`[data-field="${key}"]`);if(!el||val==null||val==='')return;el.value=String(val);el.dispatchEvent(new Event(el.tagName==='SELECT'?'change':'input',{bubbles:true}));};
const yearOf=v=>{const m=String(v||'').match(/\b(18|19|20)\d{2}\b/);return m?Number(m[0]):null;};
function isEuro(card){const c=norm(value(card,'currency')),d=norm(value(card,'denomination'));return c.includes('euro')||/^(1|2|5|10|20|50) cent$/.test(d)||/^[12] euro/.test(d);}
function scoreSeries(card,r){let s=0;const c=norm(value(card,'country')),d=norm(value(card,'denomination')),y=yearOf(value(card,'year'));const clues=norm([value(card,'referenceClues'),value(card,'obverseDesign'),value(card,'reverseDesign'),value(card,'notes')].join(' '));if(c&&norm(r.country)===c)s+=8;if(d&&norm(r.denomination)===d)s+=8;if(y&&y>=r.yearFrom&&y<=r.yearTo)s+=5;if(clues)for(const k of norm(`${r.design};${r.clues}`).split(/[;,/]/).map(x=>x.trim()).filter(x=>x.length>=3))if(clues.includes(k))s+=2;return s;}
function bestEuro(card){const c=norm(value(card,'country')),d=norm(value(card,'denomination')),y=yearOf(value(card,'year'));const regular=EURO_REFERENCE_DB.find(r=>(!c||norm(r.country)===c)&&(!d||norm(r.denomination)===d)&&(!y||(y>=r.yearFrom&&y<=r.yearTo)));const scored=EURO_SERIES_REFERENCE_DB.map(r=>({r,s:scoreSeries(card,r)})).filter(x=>x.s>0).sort((a,b)=>b.s-a.s);return {regular,series:scored[0]?.r,seriesScore:scored[0]?.s||0};}
function enrichEuroCard(card){if(!card||!isEuro(card))return;const {regular,series,seriesScore}=bestEuro(card),chosen=seriesScore>=8?series:regular;if(chosen){set(card,'currency','Euro');set(card,'country',chosen.country);set(card,'coinType',seriesScore>=8?`${series.country} ${series.denomination} — ${series.series}`:chosen.type);set(card,'referenceMatch',seriesScore>=8?'Matched to EU national-side series':'Matched to EU circulation reference');set(card,'referenceAuthority','European Commission');set(card,'referenceSource',chosen.source);set(card,'metal',chosen.composition||'');set(card,'weight',chosen.weight||'');set(card,'diameter',chosen.diameter||'');set(card,'confidence',seriesScore>=12?'High':'Medium');}const two=classifyEuroTwo({denomination:value(card,'denomination'),currency:value(card,'currency')||'Euro',year:value(card,'year'),country:value(card,'country'),referenceClues:value(card,'referenceClues'),obverseDesign:value(card,'obverseDesign'),reverseDesign:value(card,'reverseDesign'),notes:value(card,'notes')});if(two){set(card,'researchPriority',two.researchPriority);set(card,'researchReason',two.researchReason);set(card,'referenceAuthority',two.referenceAuthority);set(card,'referenceSource',two.referenceSource);set(card,'coinType',two.coinType);}else if(chosen){set(card,'researchPriority',chosen.researchPriority||'Normal');set(card,'researchReason',chosen.researchReason||'Regular euro circulation type; verify year and national-side design.');}}
const allGerman=[...GERMANY_HISTORICAL_REFERENCE_DB,...GERMANY_5DM_COMM,...GERMANY_10DM_COMM,...GERMANY_DDR_REFERENCE_DB];
function scoreGerman(card,r){let s=0;const country=norm(value(card,'country')),currency=norm(value(card,'currency')),den=norm(value(card,'denomination')),year=yearOf(value(card,'year')),mint=norm(value(card,'mintMark')),text=norm([value(card,'referenceClues'),value(card,'obverseDesign'),value(card,'reverseDesign'),value(card,'notes')].join(' '));if(country&&(country.includes('germany')||country.includes('deutschland'))&&(norm(r.country).includes('germany')))s+=5;if(currency&&currency===norm(r.currency))s+=8;if(den&&den===norm(r.denomination))s+=8;if(year&&year>=Number(r.yearFrom||0)&&year<=Number(r.yearTo||9999))s+=6;if(r.mintMark&&mint&&norm(r.mintMark).split('/').includes(mint))s+=4;for(const k of [r.subject,r.obverse,r.reverse,r.series].filter(Boolean).map(norm))if(k&&text.includes(k))s+=4;return s;}
function enrichGerman(card){if(!card||isEuro(card))return;const ranked=allGerman.map(r=>({r,s:scoreGerman(card,r)})).filter(x=>x.s>=13).sort((a,b)=>b.s-a.s);const hit=ranked[0];if(!hit)return;const r=hit.r;set(card,'country',r.country);set(card,'currency',r.currency);set(card,'coinType',r.subject?`${r.denomination} — ${r.subject}`:`${r.denomination} — ${r.series}`);set(card,'referenceMatch','Matched to official Deutsche Bundesbank historical reference');set(card,'referenceAuthority',r.authority||'Deutsche Bundesbank');set(card,'referenceSource',r.source);set(card,'metal',r.metal||'');set(card,'weight',r.weight||'');set(card,'diameter',r.diameter||'');set(card,'mintMark',r.mintMark&&r.mintMark.length===1?r.mintMark:value(card,'mintMark'));set(card,'researchPriority',r.researchPriority||r.priority||'Possibly interesting');set(card,'researchReason',r.researchReason||r.reason||'Historic German coin; verify exact year, mint and condition.');set(card,'confidence',hit.s>=22?'High':'Medium');}
document.querySelector('#records')?.addEventListener('click',e=>{const b=e.target.closest('button[data-action="verify-reference"]');if(!b)return;const id=b.closest('.record-card')?.dataset.id;setTimeout(()=>{const card=document.querySelector(`.record-card[data-id="${CSS.escape(id)}"]`);enrichEuroCard(card);enrichGerman(card);},0);});
function appendSheet(wb,name,rows){if(!rows?.length||wb.SheetNames.includes(name))return;const ws=XLSX.utils.json_to_sheet(rows);ws['!cols']=Object.keys(rows[0]).map(k=>({wch:Math.min(60,Math.max(14,k.length+2))}));XLSX.utils.book_append_sheet(wb,ws,name);}
const commRows=(arr)=>arr.map(r=>({Country:r.country,Currency:r.currency,Period:r.period,Series:r.series,Denomination:r.denomination,Subject:r.subject,'Year From':r.yearFrom,'Year To':r.yearTo||r.yearFrom,'Mint Mark':r.mintMark||'',Mintage:r.mintage||'',Metal:r.metal||'','Weight (g)':r.weight||'','Diameter (mm)':r.diameter||'',Authority:r.authority,Source:r.source,'Research Priority':r.researchPriority,'Research Reason':r.researchReason}));
const installExportHook=()=>{if(!globalThis.XLSX?.writeFile||XLSX.writeFile.__euHook)return false;const original=XLSX.writeFile.bind(XLSX);const hooked=(wb,...args)=>{appendSheet(wb,'EU Euro Circulation',euroReferenceRows());appendSheet(wb,'EU National Series',euroSeriesRows());appendSheet(wb,'EU €2 Commemorative',euroCommemorativeRows());appendSheet(wb,'Germany DM',germanyHistoricalRows());appendSheet(wb,'Germany 5DM Comm',commRows(GERMANY_5DM_COMM));appendSheet(wb,'Germany 10DM Comm',commRows(GERMANY_10DM_COMM));appendSheet(wb,'Germany DDR',germanyDdrRows());return original(wb,...args);};hooked.__euHook=true;XLSX.writeFile=hooked;return true;};if(!installExportHook())window.addEventListener('load',installExportHook,{once:true});
const status=document.querySelector('#reference-db-status');if(status){const a=euroReferenceStats(),b=euroSeriesStats();setTimeout(()=>{if(!status.textContent.includes('EU euro coverage'))status.textContent+=` EU euro coverage: ${a.issuers} issuers × ${a.denominations} denominations (${a.records} circulation references), plus ${b.series} national-side series.`;if(!status.textContent.includes('German historical coverage'))status.textContent+=` German historical coverage: DM circulation + 5/10-DM commemoratives + DDR circulation reference layer.`;},0);}
