function integral(values,width,height){const stride=width+1,out=new Float64Array((width+1)*(height+1));for(let y=0;y<height;y++){let row=0;for(let x=0;x<width;x++){row+=values[y*width+x];out[(y+1)*stride+(x+1)]=out[y*stride+(x+1)]+row;}}return out;}
function boxMean(ii,width,height,x,y,r){const stride=width+1,x0=Math.max(0,x-r),y0=Math.max(0,y-r),x1=Math.min(width-1,x+r),y1=Math.min(height-1,y+r);const sum=ii[(y1+1)*stride+(x1+1)]-ii[y0*stride+(x1+1)]-ii[(y1+1)*stride+x0]+ii[y0*stride+x0];return sum/((x1-x0+1)*(y1-y0+1));}
function binaryWindow(mask,width,height,r,mode){const ii=integral(mask,width,height),out=new Uint8Array(mask.length),stride=width+1;for(let y=0;y<height;y++)for(let x=0;x<width;x++){const x0=Math.max(0,x-r),y0=Math.max(0,y-r),x1=Math.min(width-1,x+r),y1=Math.min(height-1,y+r),sum=ii[(y1+1)*stride+(x1+1)]-ii[y0*stride+(x1+1)]-ii[(y1+1)*stride+x0]+ii[y0*stride+x0],total=(x1-x0+1)*(y1-y0+1);out[y*width+x]=mode==='dilate'?(sum>0?1:0):(sum>=total?1:0);}return out;}
function morph(mask,width,height,r){let out=binaryWindow(mask,width,height,r,'dilate');out=binaryWindow(out,width,height,r,'erode');out=binaryWindow(out,width,height,Math.max(1,Math.floor(r/2)),'erode');out=binaryWindow(out,width,height,Math.max(1,Math.floor(r/2)),'dilate');return out;}
export function candidateScore(item){const aspect=Math.min(item.width/item.height,item.height/item.width),fill=item.fill??0;const aspectScore=Math.max(0,Math.min(1,(aspect-.48)/.52)),fillScore=Math.max(0,Math.min(1,(fill-.32)/.45));return +(0.62*aspectScore+0.38*fillScore).toFixed(3);}
export function radialCandidateScore(perimeterMean,edgeThreshold,strongFraction,contrastRatio=1){if(!edgeThreshold)return 0;const edge=Math.max(0,Math.min(1,perimeterMean/(edgeThreshold*1.7))),strong=Math.max(0,Math.min(1,strongFraction/.72)),contrast=Math.max(0,Math.min(1,(contrastRatio-.95)/.55));return +(0.48*edge+0.38*strong+0.14*contrast).toFixed(3);}
function cornerBackground(data,width,height){const sx=Math.max(2,Math.round(width*.08)),sy=Math.max(2,Math.round(height*.08)),samples=[];for(const [x0,y0] of [[0,0],[width-sx,0],[0,height-sy],[width-sx,height-sy]])for(let y=y0;y<y0+sy;y+=2)for(let x=x0;x<x0+sx;x+=2){const i=(y*width+x)*4;samples.push([data[i],data[i+1],data[i+2]])}const channel=c=>{const a=samples.map(s=>s[c]).sort((a,b)=>a-b);return a[Math.floor(a.length/2)]||0};return [channel(0),channel(1),channel(2)];}
export function backgroundDistance(r,g,b,bg){return Math.hypot(r-bg[0],g-bg[1],b-bg[2]);}
function components(mask,width,height){const seen=new Uint8Array(mask.length),found=[],areaAll=width*height,dirs=[-1,1,-width,width,-width-1,-width+1,width-1,width+1];for(let start=0;start<mask.length;start++){if(!mask[start]||seen[start])continue;const stack=[start];seen[start]=1;let area=0,minX=width,maxX=0,minY=height,maxY=0;while(stack.length){const p=stack.pop(),y=Math.floor(p/width),x=p-y*width;area++;minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);for(const d of dirs){const q=p+d;if(q<0||q>=mask.length||seen[q]||!mask[q])continue;const qy=Math.floor(q/width),qx=q-qy*width;if(Math.abs(qx-x)>1||Math.abs(qy-y)>1)continue;seen[q]=1;stack.push(q);}}const w=maxX-minX+1,h=maxY-minY+1,aspect=w/h,fill=area/(w*h),share=area/areaAll;if(share<0.0025||share>0.72||aspect<0.45||aspect>2.20||fill<0.30)continue;const item={x:minX,y:minY,width:w,height:h,area,fill,cx:(minX+maxX)/2,cy:(minY+maxY)/2};item.score=candidateScore(item);if(item.score>=.24)found.push(item);}return found;}
function gradientMap(gray,width,height){const grad=new Float32Array(gray.length),sample=[];for(let y=1;y<height-1;y++)for(let x=1;x<width-1;x++){const p=y*width+x,gx=gray[p+1]-gray[p-1],gy=gray[p+width]-gray[p-width],g=Math.hypot(gx,gy);grad[p]=g;if((x+y)%7===0)sample.push(g);}sample.sort((a,b)=>a-b);const threshold=Math.max(8,sample[Math.floor(sample.length*.72)]||8);return {grad,threshold};}
function ringStats(grad,width,height,cx,cy,r,samples=40,threshold=0){let sum=0,strong=0,valid=0,longest=0,run=0,firstRun=0,lastRun=0;for(let k=0;k<samples;k++){const a=2*Math.PI*k/samples,x=Math.round(cx+Math.cos(a)*r),y=Math.round(cy+Math.sin(a)*r);if(x<1||y<1||x>=width-1||y>=height-1){run=0;continue;}const g=grad[y*width+x],isStrong=g>=threshold;sum+=g;valid++;if(isStrong){strong++;run++;longest=Math.max(longest,run);if(k===firstRun)firstRun++;}else run=0;if(k===samples-1)lastRun=run;}longest=Math.max(longest,firstRun+lastRun);return {mean:valid?sum/valid:0,strongFraction:valid?strong/valid:0,continuity:valid?Math.min(1,longest/Math.max(1,Math.round(valid*.22))):0};}
function ringMean(grad,width,height,cx,cy,r,samples=28){return ringStats(grad,width,height,cx,cy,r,samples).mean;}
export function clusterCircleCandidates(items,{centerFactor=.42,radiusRatio=.55}={}){const kept=[];for(const item of [...items].sort((a,b)=>(b.score??0)-(a.score??0))){const r=Math.max(1,(item.width+item.height)/4);if(kept.some(k=>{const kr=Math.max(1,(k.width+k.height)/4),center=Math.hypot(item.cx-k.cx,item.cy-k.cy),ratio=Math.min(r,kr)/Math.max(r,kr);return center<=Math.min(r,kr)*centerFactor&&ratio>=radiusRatio;}))continue;kept.push(item);}return kept;}
function radialCircles(gray,width,height){const {grad,threshold}=gradientMap(gray,width,height),minDim=Math.min(width,height),radii=[];for(let r=Math.max(14,minDim*.025);r<=minDim*.22;r*=1.28)radii.push(Math.round(r));const out=[];for(const r of radii){const step=Math.max(5,Math.round(r*.28)),samples=40;for(let cy=r+2;cy<height-r-2;cy+=step)for(let cx=r+2;cx<width-r-2;cx+=step){const ring=ringStats(grad,width,height,cx,cy,r,samples,threshold),inner=ringMean(grad,width,height,cx,cy,r*.72,24),outer=ringMean(grad,width,height,cx,cy,r*1.18,24),contrast=ring.mean/Math.max(1,(inner+outer)/2),score=radialCandidateScore(ring.mean,threshold,ring.strongFraction,contrast);if(score>=.59&&ring.strongFraction>=.43&&ring.continuity>=.72)out.push({x:cx-r,y:cy-r,width:2*r,height:2*r,area:Math.PI*r*r,fill:.785,cx,cy,score,source:'radial'});}}return nonMaxSuppression(clusterCircleCandidates(out),.30).slice(0,24);}
export function boxIoU(a,b){const x1=Math.max(a.x,b.x),y1=Math.max(a.y,b.y),x2=Math.min(a.x+a.width,b.x+b.width),y2=Math.min(a.y+a.height,b.y+b.height),inter=Math.max(0,x2-x1)*Math.max(0,y2-y1);if(!inter)return 0;return inter/(a.width*a.height+b.width*b.height-inter);}
export function nonMaxSuppression(items,threshold=.42){const kept=[];for(const item of [...items].sort((a,b)=>(b.score??0)-(a.score??0))){if(kept.every(k=>boxIoU(item,k)<threshold))kept.push(item);}return kept;}
function sortReadingOrder(items){if(items.length<2)return items;const avgH=items.reduce((s,i)=>s+i.height,0)/items.length,tolerance=avgH*.55,rows=[];for(const item of [...items].sort((a,b)=>a.cy-b.cy||a.cx-b.cx)){let row=rows.find(r=>Math.abs(r.cy-item.cy)<=tolerance);if(!row){row={cy:item.cy,items:[]};rows.push(row)}row.items.push(item);row.cy=row.items.reduce((s,i)=>s+i.cy,0)/row.items.length;}rows.sort((a,b)=>a.cy-b.cy);return rows.flatMap(r=>r.items.sort((a,b)=>a.cx-b.cx));}
export function pairByNormalizedPosition(frontBoxes,backBoxes,frontSize,backSize,{maxDistance=.18}={}){if(!frontBoxes?.length||frontBoxes.length!==backBoxes?.length)return {pairs:[],confidence:'none',maxDistance:null};const norm=(b,s)=>({x:(b.x+b.width/2)/s.width,y:(b.y+b.height/2)/s.height});const available=new Set(backBoxes.map((_,i)=>i)),pairs=[];let worst=0,total=0;for(let i=0;i<frontBoxes.length;i++){const f=norm(frontBoxes[i],frontSize);let best=-1,bestD=Infinity;for(const j of available){const b=norm(backBoxes[j],backSize),d=Math.hypot(f.x-b.x,f.y-b.y);if(d<bestD){bestD=d;best=j;}}if(best<0||bestD>maxDistance)return {pairs:[],confidence:'low',maxDistance:bestD};available.delete(best);pairs.push([i,best]);worst=Math.max(worst,bestD);total+=bestD;}const avg=total/pairs.length,confidence=worst<=.07&&avg<=.045?'high':worst<=.12&&avg<=.08?'medium':'low';return {pairs,confidence,maxDistance:worst,averageDistance:avg};}
async function bitmapFromBlob(blob){if(globalThis.createImageBitmap)return createImageBitmap(blob);const url=URL.createObjectURL(blob);try{return await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=url})}finally{URL.revokeObjectURL(url)}}
export async function detectCoins(blob,{maxDimension=700}={}){const bitmap=await bitmapFromBlob(blob),sourceWidth=bitmap.width,sourceHeight=bitmap.height,scale=Math.min(1,maxDimension/Math.max(sourceWidth,sourceHeight)),width=Math.max(1,Math.round(sourceWidth*scale)),height=Math.max(1,Math.round(sourceHeight*scale)),canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(bitmap,0,0,width,height);const data=ctx.getImageData(0,0,width,height).data,gray=new Float32Array(width*height),sat=new Float32Array(width*height),bg=cornerBackground(data,width,height);for(let i=0,p=0;i<data.length;i+=4,p++){const r=data[i],g=data[i+1],b=data[i+2],max=Math.max(r,g,b),min=Math.min(r,g,b);gray[p]=.299*r+.587*g+.114*b;sat[p]=max-min;}const radius=Math.max(24,Math.round(Math.min(width,height)*.08)),gi=integral(gray,width,height),si=integral(sat,width,height),mask=new Uint8Array(width*height);for(let y=0;y<height;y++)for(let x=0;x<width;x++){const p=y*width+x,i=p*4,gMean=boxMean(gi,width,height,x,y,radius),sMean=boxMean(si,width,height,x,y,radius),contrast=Math.abs(gMean-gray[p]),satContrast=Math.abs(sat[p]-sMean),bgDistance=backgroundDistance(data[i],data[i+1],data[i+2],bg);if(contrast>8||satContrast>14||bgDistance>34)mask[p]=1;}const mr=Math.max(1,Math.round(Math.min(width,height)*.0035)),cleaned=morph(mask,width,height,mr),componentCandidates=components(cleaned,width,height),circleCandidates=radialCircles(gray,width,height),detected=sortReadingOrder(nonMaxSuppression([...componentCandidates,...circleCandidates],.38));const boxes=detected.map((d,index)=>{const pad=Math.round(Math.max(d.width,d.height)*.08),x=Math.max(0,d.x-pad),y=Math.max(0,d.y-pad),x2=Math.min(width,d.x+d.width+pad),y2=Math.min(height,d.y+d.height+pad),score=d.score;return {index:index+1,x:x/scale,y:y/scale,width:(x2-x)/scale,height:(y2-y)/scale,score,confidence:score>=.75?'high':score>=.56?'medium':'low',detector:d.source||'component'};});bitmap.close?.();return {count:boxes.length,boxes,analysisWidth:width,analysisHeight:height,sourceWidth,sourceHeight};}
export async function cropCoin(blob,box,type='image/jpeg'){const bitmap=await bitmapFromBlob(blob),canvas=document.createElement('canvas'),x=Math.max(0,Math.floor(box.x)),y=Math.max(0,Math.floor(box.y)),w=Math.min(bitmap.width-x,Math.ceil(box.width)),h=Math.min(bitmap.height-y,Math.ceil(box.height));canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(bitmap,x,y,w,h,0,0,w,h);bitmap.close?.();return await new Promise(resolve=>canvas.toBlob(resolve,type==='image/png'?'image/png':'image/jpeg',.92));}
