import './coin-depth.js';
import { WORLD_BATCH04_COUNTRIES, WORLD_BATCH04_REFERENCE_DB, worldBatch04ExcelRows, worldBatch04Stats } from './world-batch04-reference.mjs';

const norm=v=>String(v||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ');
const field=(card,key)=>card?.querySelector(`[data-field="${key}"]`)?.value||'';
const setField=(card,key,value)=>{const el=card?.querySelector(`[data-field="${key}"]`);if(!el||value==null||value==='')return;el.value=String(value);el.dispatchEvent(new Event(el.tagName==='SELECT'?'change':'input',{bubbles:true}));};
const yearOf=v=>{const m=String(v||'').match(/\b(17|18|19|20)\d{2}\b/);return m?Number(m[0]):null;};
function identify(snapshot){const c=norm(snapshot.country);let hits=WORLD_BATCH04_COUNTRIES.filter(x=>c&&x.aliases.some(a=>c===norm(a)||c.includes(norm(a))));if(hits.length===1)return hits[0];const currency=norm(snapshot.currency);hits=WORLD_BATCH04_COUNTRIES.filter(x=>currency&&x.currencyAliases.some(a=>currency===norm(a)||currency.includes(norm(a))));return hits.length===1?hits[0]:null;}
function score(row,s){let score=0;const d=norm(s.denomination),year=yearOf(s.year),visible=norm(s.visible);if(d&&(norm(row.denomination)===d||norm(row.denomination).split(' / ').includes(d)))score+=12;else if(d&&norm(row.denomination).includes(d))score+=6;if(year&&year>=Number(row.yearFrom)&&year<=Number(row.yearTo))score+=10;if(visible&&norm(`${row.series} ${row.obverse} ${row.reverse} ${row.type}`).split(' ').some(token=>token.length>4&&visible.includes(token)))score+=3;if(row.scope==='Priority historical')score+=2;return score;}
function choose(country,s){return WORLD_BATCH04_REFERENCE_DB.filter(r=>r.country===country.country).map(row=>({row,score:score(row,s)})).sort((a,b)=>b.score-a.score)[0]||null;}
function apply(card,hit){const r=hit.row;setField(card,'country',r.country);setField(card,'currency',r.currency);setField(card,'period',r.period);setField(card,'coinType',`${r.denomination} — ${r.series}`);setField(card,'mintMark',r.mintMark);setField(card,'metal',r.metal);if(r.weight!=null)setField(card,'weight',r.weight);if(r.diameter!=null)setField(card,'diameter',r.diameter);setField(card,'obverseDesign',r.obverse);setField(card,'reverseDesign',r.reverse);setField(card,'edgeDescription',r.edge);setField(card,'referenceMatch',`${r.scope}: ${r.series}`);setField(card,'referenceAuthority',r.authority);setField(card,'referenceSource',r.source);setField(card,'researchPriority',r.researchPriority);setField(card,'researchReason',`${r.researchReason} Metadata: ${r.metadataStatus}.`);setField(card,'confidence',hit.score>=20?'High':hit.score>=12?'Medium':'Low');}
document.querySelector('#records')?.addEventListener('click',event=>{if(!event.target.closest('button[data-action="verify-reference"]'))return;const card=event.target.closest('.record-card');if(!card)return;const id=card.dataset.id;const snapshot={country:field(card,'country'),currency:field(card,'currency'),denomination:field(card,'denomination'),year:field(card,'year'),visible:field(card,'visibleText')};const country=identify(snapshot);if(!country)return;const hit=choose(country,snapshot);if(!hit)return;setTimeout(()=>{const fresh=document.querySelector(`.record-card[data-id="${CSS.escape(id)}"]`);if(fresh)apply(fresh,hit);},0);});
function appendSheet(wb,name,rows){if(!rows.length||wb.SheetNames.includes(name))return;const ws=XLSX.utils.json_to_sheet(rows);ws['!cols']=Object.keys(rows[0]).map(k=>({wch:Math.min(65,Math.max(14,k.length+2))}));XLSX.utils.book_append_sheet(wb,ws,name);}
function install(){if(!globalThis.XLSX?.writeFile||XLSX.writeFile.__world04Hook)return false;const prev=XLSX.writeFile.bind(XLSX);const hook=(wb,...args)=>{appendSheet(wb,'North America Priority',worldBatch04ExcelRows());return prev(wb,...args);};hook.__world04Hook=true;XLSX.writeFile=hook;return true;}if(!install())window.addEventListener('load',install,{once:true});
const status=document.querySelector('#reference-db-status');if(status){const s=worldBatch04Stats();setTimeout(()=>{if(!status.textContent.includes('North America priority'))status.textContent+=` North America priority: ${s.records} records for ${s.countries} countries — ${s.historical} historical priority, ${s.selectedModern} selected modern-interest and ${s.modernBaseline} compact modern baseline rows.`;},0);}
